FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1 \
    v4l-utils \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-worker.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# YOLOv8 models usually download on first run, we can preload them if needed, but it's fine for MVP
# Start Worker
CMD ["python", "-m", "apps.worker.main"]
